<br />
<a href="#" onclick="motd$1d.style.display=(motd$1d.style.display=='inline'?'none':'inline');return false;" style="background: activecaption; color: captiontext; text-decoration: none;"><b>MOTD:</b></a>
For your conveniance, the <i>message of the day</i> is hidden by default but might contain important notices to users of this server. <i>Including you.</i><br />

<div id="motd$1d" style="display:none;"><div class="motd"><span id="motd$1"></span></div></div>
<a href="#" onclick="motd$1d.style.display=(motd$1d.style.display=='inline'?'none':'inline');return false;">Click here</a>
to toggle the motd.<br />
<br />
